[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Exclude the brevis directory from the build for now -> stack too deep error
exclude = ["src/brevis"]

solc_version = '0.8.26'
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
via_ir = true
ffi = true

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[profile.coverage]
optimizer = true
optimizer_runs = 1000000
via_ir = true
src = ["src", "!src/brevis"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
